name: database
description: Manage project data when you don't have an API connection.
version: 0.0.1
publish_to: none
homepage: 'null'
environment:
  sdk: ">=2.19.3 <3.0.0"
  flutter: ">=3.7.6"

dependencies:
  floor: ^1.4.2
  flutter:
    sdk: flutter
  sqflite: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  floor_generator: ^1.4.2

